### ISSUE TITLE
Support precise specification for multiple scopes

### ISSUE THREAD

**Issue by stmeissner** [commercetools/commercetools-docs-kit#1129]
In our APIs we need to document two different cases for OAuth scopes.

1. either scope A is required **or** scope B
2. scope A **and** scope B are required

Currently the kit shows the scopes in a comma separated list what leaves it unclear for the reader which of the scopes are required at minimum.

`view_customers:{projectKey},view_customer_groups:{projectKey} `

The RAML spec for this assumes that one or the other scope is sufficient for the API endpoint when modelled like so:

```
  securedBy:
  - oauth_2_0:
      scopes:
      - "view_customers:{projectKey}"
      - "view_customer_groups:{projectKey}"
```

This is working fine, but what we also need is a way to document that both (or more) scopes are required. Currently, when having this in the flattened RAML spec:

```
  securedBy:
  - oauth_2_0:
      scopes:
      - "view_customers:{projectKey}"
  - oauth_2_0:
      scopes:
      - "view_customer_groups:{projectKey}"
```
### Current behavior
only the first scope is rendered on the page. 
### Desired behavior
both (or more) scopes are rendered on the page and marked as conjunction.
