### ISSUE TITLE
multi-line string in description of enum definition list

### ISSUE THREAD

**Issue by TohruKohrita** [commercetools/commercetools-docs-kit#1142]
We often use multiline string in raml description fields. We usually use a vertical line "|" to do so. 

But when it come to an enum definition list, if you use "|" to start a multiline string, line breaks get rendered as "n".
If you use ">", no such problem arises. This may be an expected yaml behavior (I did a quick internet search on this), but let me report this because "|" always works fine but not in this case alone.

Here is an example.

<img width="367" alt="Screenshot 2021-11-15 at 10 04 38" src="https://user-images.githubusercontent.com/63338357/141753059-32940cbe-7ea8-47c4-8415-cc5f5b912f25.png">
 
becomes

<img width="613" alt="Screenshot 2021-11-15 at 10 11 20" src="https://user-images.githubusercontent.com/63338357/141754026-5be7734b-535d-4baa-b298-d6fd1c390685.png">

The smoke test did not really test this. https://github.com/commercetools/commercetools-docs-kit/blob/main/api-specs/test/types/enums.raml#L53

**Comment by nkuehn** [comment]
Yes, this can be considered a bug.

**Comment by nkuehn** [comment]
Debug result:  It's a bug in rmf-codegen.

input:
```yaml
  EnumWithDescriptionExample:
    description: Enum with agreed upon description annotation.
    type: string
    (annotations.enumDescriptions):
      enumValue1: Description 1
      enumValue2: |
        Description 2 with a line break (first line)
        Second line.

        New paragraph.
      enumWithMarkdownDescription: |
        `inline-code` should be formatted as an inline code. [ObjectTestType](/types/general#objecttesttype) should link to the header of the definition of `ObjectTestType` on this website - `api-docs-smoke-test`. [Links](/../docs-smoke-test/views/markdown#links) should link to the header for the definition of  `Links` on `docs-smoke-test` microsite.
    enum:
      - enumValue1
      - enumValue2
      - enumWithoutDescription
      - enumWithMarkdownDescription
```

output in RAML_DOC:

```yaml
#%RAML 1.0 DataType
displayName: EnumWithDescriptionExample
description: |-
  Enum with agreed upon description annotation.
type: string
enum:
- enumValue1
- enumValue2
- enumWithoutDescription
- enumWithMarkdownDescription
(enumDescriptions):
  enumValue1: "Description 1"
  enumValue2: "Description 2 with a line break (first line)nSecond line.nnNew paragraph."
  enumWithMarkdownDescription: "`inline-code` should be formatted as an inline code.
   [ObjectTestType](/types/general#objecttesttype) should link to the header of the
   definition of `ObjectTestType` on this website - `api-docs-smoke-test`. [Links](/../docs-smoke-test/views/markdown#links)
   should link to the header for the definition of  `Links` on `docs-smoke-test`
   microsite."
```

The multiline string gets lost in the RAML_DOC output.
