### ISSUE TITLE
Error rendering Request Body when uploading image to Products

### ISSUE THREAD

**Issue by industrian** [commercetools/commercetools-docs-kit#1324]
I'm currently working on the [RAML for Products PR](https://github.com/commercetools/commercetools-docs/pull/1933) and noticed the following error under Request Body:

![image](https://user-images.githubusercontent.com/77231096/173784900-00cde174-28c0-43fc-bd5a-5728b03b1ba6.png)

This is how it appears in RAML (`products.raml`):

![image](https://user-images.githubusercontent.com/77231096/173833065-03256f51-a244-4b1c-ab66-c6af7b226410.png)

This is how correctly in the flattened version of the endpoint (in `ByProjectKeyProductsByIdImages.raml`):

![image](https://user-images.githubusercontent.com/77231096/173832923-8e4454ef-1267-46bd-b7b6-c00da53ed6da.png)

I'm curious if this is caused by a missing feature in Docs Kit.

**Comment by jenschude** [comment]
You are right the modelling is not good atm.

```
  body:
    application/json:
      fileTypes: [image/jpeg, image/png, image/gif]
      type: file
      (builtinType): file
```

This is what the codegen is generating atm. The raml spec is a little bit underspecified here. Especially as it says it SHOULD be json.

When we want to specify the bodies is has to be like this:

```
body:
  image/jpeg:
    type: file
  image/png:
    type: file
  image/gif
    type: file
```

As leaving out any typ information raml says the default should be a string type. And i don't think that the spec takes into consideration that the mime-type may resort to file type.
