### ISSUE TITLE
Follow up: Regex properties on non-string types

### ISSUE THREAD

**Issue by industrian** [commercetools/commercetools-docs-kit#1368]
Original issue: https://github.com/commercetools/commercetools-docs-kit/issues/1357

In a recent update, this functionality was added to the kit.

The description in a work-in-progress document appears to be "off" though:

It's "Array of Any object property matching this regular expression" when it should be "Array of Suggestion":

![image](https://user-images.githubusercontent.com/77231096/191608076-f983ca4e-8486-4107-96d2-6b36b4cbf1f4.png)

![image](https://user-images.githubusercontent.com/77231096/191608100-d1842e4a-0402-4925-ac59-bcd56015dbe7.png)

This was discussed at the Team weekly on 21 September.

**Comment by gabriele-ct** [comment]
Looking at api-specs/history/types/common/SearchKeywords.raml
seems that the expected structure is like this:

```
#%RAML 1.0 DataType
(package): Common
type: object
displayName: SearchKeywords
description:
properties:
  /^[a-z]{2}(-[A-Z]{2})?$/:
    type: array
    items:
      type: SearchKeyword
```


Could @industrian  please check if the actual Product definition in api-specs/api/types/product/SuggestionResult.raml is correct of is missing the `type` property
