### ISSUE TITLE
Add support for default values of query parameters

### ISSUE THREAD

**Issue by stmeissner** [commercetools/commercetools-docs-kit#1435]
We have the need to document the default value for a query parameter, but this is currently not supported by the Docs Kit.

Given this RAML spec:

```yaml
queryParameters:
      staged?:
        type: boolean
        default: false
```
The rendered page should show the same box on the respective query parameter as for default values on data types.
![default-false](https://user-images.githubusercontent.com/900598/203322706-ffe88b68-c382-489e-9e56-22022194f909.png)
