### ISSUE TITLE
Add support for Union types in RAML docs

### ISSUE THREAD

**Issue by stmeissner** [commercetools/commercetools-docs-kit#1483]
I have some union type to render from RAML that is encoded like this in the flattened RAML spec:
```yaml
properties:
  reference:
    type: CartReference | OrderReference
    (oneOf):
    - CartReference
    - OrderReference
    (builtinType): any
    description: |-
      Reference to a [Cart](ctp:api:type:Cart) or [Order](ctp:api:type:Order) that is replicated.
    required: true
    (inherited): false
 ```
I expected to see something like  "[CartReference]() or [OrderReference]()"  rendered for the `reference` property, but instead I get just "Union".
![Union](https://user-images.githubusercontent.com/900598/212317753-d755a21e-e441-4ce7-a2e0-0a85b10fe323.png)

Could you please add support for this for RAML types also? For query parameters we have something like that already:
![union parameter](https://user-images.githubusercontent.com/900598/212319616-2f49e576-2f2a-4b75-b862-d92a9f164455.png)
