### ISSUE TITLE
Support clickable chapter titles

### ISSUE THREAD

**Issue by timonrey** [commercetools/commercetools-docs-kit#1720]
The tech writers are preparing to restructure the content of each microsite so that every chapter has it's own overview page. This page would reachable through a clickable chapter title. At the moment, we do not support this as we expect the paths to the pages to be only defined under `pages` of each chapter in the `navigation.yaml` file.

In the future, we would support this navigation structure: (suggestion)

```yaml
- chapter-title: Views
  path: /views/overview
  pages:
    - title: Markdown
      path: /views/markdown
    - title: Empty
      path: /views/empty
- chapter-title: Components
  path: /components/overview
  beta: true
  pages:
    - title: Code blocks
      path: /components/code-blocks
    - title: Code Examples
      path: /components/code-examples
```

**Requirements:**
This still needs some UX/UI discussion for the clickable chapter titles

**Keep in mind**
The tech writers team would like to do one big release enabling clickable chapter titles for all microsites. So as long as we don't want to implement this feature as a flag (only for a limited time, it should be a requirement to have pages for every chapter title in the feature), it would be a big breaking change.
I would recommend to implement this feature at the right time. It shouldn't be too late so that the tech writers are not blocked and are able to see it in the preview, but also not too soon as it would be a breaking change, blocking all other releases for some time.
