### ISSUE TITLE
Enum description is not rendered when enum value is `enum`

### ISSUE THREAD

**Issue by stmeissner** [commercetools/commercetools-docs-kit#1962]
I know the title sounds a bit weird, but I can explain the case:

### Context

I have following enum type specified in RAML:

```yaml
#%RAML 1.0 DataType
type: string
enum:
  - enum
  - lenum
(enumDescriptions):
  enum: |
    For enum fields and Attributes.
  lenum: |
    For localized enum fields and Attributes.
```
When I embed this RAML type to a Markdown page: 

```html
### EnumType

<ApiType apiKey="api" type="MyEnumType" />
```

### Current behavior

The description for the `enum` value is not displayed:
![description for enum value not displayed](https://github.com/commercetools/commercetools-docs-kit/assets/900598/12e6733c-eee4-409d-8133-ec99313d3f29)

### Expected behavior

The description for the `enum` value "For enum fields and Attributes." is displayed.
